USE CELLERY_HUB;
INSERT INTO `REGISTRY_ORGANIZATION` (ORG_NAME, DESCRIPTION, WEBSITE_URL, DEFAULT_IMAGE_VISIBILITY, FIRST_AUTHOR, CREATED_DATE) VALUES ('cellery','ABC is my first org','abc.com','private','unknown','2019-05-27 14:58:47');
INSERT INTO `REGISTRY_ORGANIZATION` (ORG_NAME, DESCRIPTION, WEBSITE_URL, DEFAULT_IMAGE_VISIBILITY, FIRST_AUTHOR, CREATED_DATE) VALUES ('is','ABC is my first org','pqr.com','private','unknown','2019-05-27 14:58:47');
INSERT INTO `REGISTRY_ORG_USER_MAPPING` (USER_UUID, ORG_NAME, USER_ROLE, CREATED_DATE) VALUES ('wso2.com','cellery','push','2019-04-06 00:00:00');
INSERT INTO `REGISTRY_ORG_USER_MAPPING` (USER_UUID, ORG_NAME, USER_ROLE, CREATED_DATE) VALUES ('admin.com','cellery','admin','2019-04-06 00:00:00');
INSERT INTO `REGISTRY_ORG_USER_MAPPING` (USER_UUID, ORG_NAME, USER_ROLE, CREATED_DATE) VALUES ('other.com','is','pull','2019-04-06 00:00:00');
INSERT INTO `REGISTRY_ARTIFACT_IMAGE` (ARTIFACT_IMAGE_ID, ORG_NAME, IMAGE_NAME, DESCRIPTION, FIRST_AUTHOR, VISIBILITY) VALUES ('1','cellery','image','Sample','unkown','PUBLIC');
INSERT INTO `REGISTRY_ARTIFACT_IMAGE` (ARTIFACT_IMAGE_ID, ORG_NAME, IMAGE_NAME, DESCRIPTION, FIRST_AUTHOR, VISIBILITY) VALUES ('2','cellery','newImage','Sample','www.dockehub.com','PRIVATE');
INSERT INTO `REGISTRY_ARTIFACT_IMAGE` (ARTIFACT_IMAGE_ID, ORG_NAME, IMAGE_NAME, DESCRIPTION, FIRST_AUTHOR, VISIBILITY) VALUES ('3','is','pqr','Sample','www.dockehub.com','PRIVATE');
